ProyectoDesarrollo.B.P/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class ProductoController : Controller
    {
        private readonly iProducto _producto;
        public ProductoController(iProducto producto)
        {
            _producto = producto;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Producto/Comprar/{Codigo}")]
        public IActionResult Comprar(string codigo)
        {
            return View(_producto.GetaProducto(codigo));
        }
        public IActionResult Catalogo()
        {
            return View(_producto.MostrarTodosProductos());
        }
    }
   


}

ProyectoDesarrollo.B.P/Controllers/ProyectoController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class ProyectoController : Controller
    {
        private readonly IUsuario _usuario;
        public ProyectoController(IUsuario usuario)
        {
            _usuario = usuario;
        }
        public IActionResult Index()
        {
            return View();
        }
    
        public IActionResult Registro()
        {
            return View();
        }
        public IActionResult Listar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _usuario.Add(usuario);
                var lst = _usuario.GellAllUser();
                return View(lst);
            }
            else
            {
                return View("Registro");
            }
        }
		[Route("usuario/cargar/{codigo}")]
		public IActionResult Cargar(string codigo)
		{
			ViewData["cod"] = codigo;
			return View();
		}
        public IActionResult RegistroProducto()
        {
            return View();
        }
        public IActionResult Pagar()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Principal()
        {
            return View();
        }
    }

}

ProyectoDesarrollo.B.P/Controllers/TemporalVentaController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class TemporalVentaController : Controller
    {
        private readonly iTemporalVenta _temporalVenta;

        public TemporalVentaController(iTemporalVenta temporalVenta)
        {
            _temporalVenta = temporalVenta;
        }

        public IActionResult Index(string txtcodigo, string txtdescripcion, string txtprecio, string txtcantidad)
        {
            TemporalVenta obj = new TemporalVenta();
            int  productoExistente = _temporalVenta.ObtenerProductoPorCodigo(txtcodigo);

            if (productoExistente != -1)
            {

                _temporalVenta.AumentarCantidadProducto(txtcodigo, int.Parse(txtcantidad));
  
            }
            else
            {  
               
                obj.codigo = txtcodigo;
                obj.nombre = txtdescripcion;
                obj.precio = double.Parse(txtprecio);
                obj.cantidad = int.Parse(txtcantidad);

                _temporalVenta.agregar(obj);
           }

            return RedirectToAction("Catalogo", "Producto");
        }

      
        [Route("TemporalVenta/VerCarrito/{Codigo}")]
        public IActionResult EliminarProducto(string codigo)
        {
            _temporalVenta.EliminarProducto(codigo);

            return RedirectToAction("VerCarrito");
        }
        public IActionResult VerCarrito()
        {
            return View(_temporalVenta.ListarTemporalVenta());
        }
        public IActionResult VerCombo()
        {
            return View();
        }

        public IActionResult VerDetalle()
        {
            return View(_temporalVenta.ListarTemporalVenta());
        }
    }
}

ProyectoDesarrollo.B.P/Views/Proyecto/Cargar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>

<body>
    <h1>CARGAR:</h1>
    <h2>@ViewData["cod"]</h2> 
</body>




</html>

ProyectoDesarrollo.B.P/Views/Proyecto/Index.cshtml
<html>
<head>
	<link rel="stylesheet" href="~/css/Style.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

</head>

<body>

	<div class="barra">
		<div class="elementobarra" role="group">
			<button class="btn btn-default" onclick="history.back()"><span class="glyphicon glyphicon-chevron-left"></span></button>
			<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-user"></span><a asp-action="Registro">Registro</a></button>
			<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"><a asp-controller="TemporalVenta"  asp-action="VerCarrito">Carrito</a></span></button>
			<button class="btn btn-default"><span class="glyphicon glyphicon-handbag"> <a asp-controller="Producto" asp-action="Catalogo">Catalogo</a></span></button>



		</div>
	</div>
	<h1 style="text-align: center;"> Lista de productos </h1>
	<div class="cuadrícula-de-productos">
		<div class="fila">
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9mDXFmtO6DWgzHYYBf1ErbWGppZ0zSYs1Qg&usqp=CAU"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Comeedero</p>
					<p class="precio-del-producto">S/ 46.00</p>
				</div>
			</div>
			<div class="elemento-de-producto elemento-de-producto-derecho">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://dpq25p1ucac70.cloudfront.net/seller-place-files/mrkl-files/589/MARKETPLACE%20INTERNACIONAL/41m2baKoNCL_000044130312_22.jpeg"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Cama inflable</p>
					<p class="precio-del-producto">S/ 79.90</p>
				</div>
			</div>
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRerJxu4HnmfSmzYdMKj16HMhSdXyxPl_O-sQ&usqp=CAU"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Manguera masajeadora</p>
					<p class="precio-del-producto">S/ 49.00</p>
				</div>
			</div>
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://ae01.alicdn.com/kf/He2333eff7255495290844f86e6d27088L/Katu-Bandanas-con-patr-n-de-hueso-para-mascota-accesorios-para-perros-peque-os-medianos-y.jpg_Q90.jpg_.webp"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Katu Bandas</p>
					<p class="precio-del-producto">S/ 16.60</p>
				</div>
			</div>
		</div>
		<div class="fila">
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://http2.mlstatic.com/D_NQ_NP_975963-CBT50167523122_062022-W.jpg"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Pechera</p>
					<p class="precio-del-producto">S/ 52.90</p>
				</div>
			</div>
			<div class="elemento-de-product">

				<div class="detalles-del-producto">
					<img class="imagen-de-producto" src="https://home.ripley.com.pe/Attachment/WOP_5/Arrocito_Pet_Shop/ARC-005%20XL%20CASTA%C3%91O.jpg"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Collar</p>
					<p class="precio-del-producto">S/ 89.90</p>
				</div>
			</div>
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto con-borde" src="https://ae01.alicdn.com/kf/H0f12e050b1234b8aa4750533db88596fC.jpg"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Hueso masticable</p>
					<p class="precio-del-producto">S/ 13.50</p>
				</div>
			</div>
			<div class="elemento-de-producto">
				<div class="detalles-del-producto">
					<img class="imagen-de-producto con-borde" src="https://www.molitalia.com.pe/wp-content/uploads/2020/09/Dummie-Nutrican-Adultos-x-450g.jpg"
						 width="250" height="250" alt="Imagen del producto">
					<p class="nombre-del-producto">Comida para Perros</p>
					<p class="precio-del-producto">S/ 19.90</p>
				</div>
			</div>

		</div>
		</div>
	<section>
		<div class="form-group">
		</div>
		<div class="text-dark">
		</div>

		<h2>Contacto</h2>
		<form action="#" method="post">
			<label for="nombre">Nombre:</label>
			<input type="text" id="nombre" name="nombre">
			<label for="correo">Correo electrónico:</label>
			<input type="email" id="correo" name="correo">
			<label for="mensaje">Mensaje:</label>
			<textarea id="mensaje" name="mensaje"></textarea>
			<input type="submit" value="Enviar">
		</form>
	</section>
	<footer>
		<p> </p>
		<p> </p>
		<p>. </p>

	</footer>
</body>
</html>

ProyectoDesarrollo.B.P/Views/Proyecto/ListarUsuario.cshtml
@model IEnumerable<ProyectoDesarrollo.B.P.Models.Usuario>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>
<body>
    <table border="2">
        <tr>
            <td>CODIGO</td>
            <td>NOMBRE</td>
            <td>APELLIDO</td>
            <td>EDAD</td>
            <td>CARGAR</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nombre</td>
                <td>@item.Apellido</td>
                <td>@item.Edad</td>
                <td><a asp-action="Cargar" asp-route-id="@item-Id">Cargar</a></td>
            </tr>
        }
    </table>
</body>
</html>

ProyectoDesarrollo.B.P/Views/Proyecto/Login.cshtml
<html>
<head>
    <link rel="stylesheet" href="~/css/estiloLogin.css">

</head>
<body class="login">
    <div id="particles-js"></div>
    <div class="container">
        <div class="login-container-wrapper clearfix">
            <div class="logo">
                <i class="fa fa-sign-in"></i>
            </div>
            <div class="welcome"><strong>Welcome,</strong> please login</div>

            <form class="form-horizontal login-form">
                <div class="form-group relative">
                    <input id="login_username" class="form-control input-lg" type="email" placeholder="Username" required>
                    <i class="fa fa-user"></i>
                </div>
                <div class="form-group relative password">
                    <input id="login_password" class="form-control input-lg" type="password" placeholder="Password" required>
                    <i class="fa fa-lock"></i>
                </div>
                <div class="form-group">

                    <input type="button" value="Login" onclick="location.href='@Url.Action("Index")'" class="btn btn-success btn-lg btn-block" />

                </div>
                <div class="checkbox pull-left">
                    <label><input type="checkbox"> Remember</label>
                </div>
                <div class="checkbox pull-right">
                    <label> <a class="forget" href="" title="forget">Forgot your password</a> </label>
                </div>
            </form>
            <a asp-action="registro">Registro de Usuario</a>
        </div>

        <h4 class="text-center">
            <a target="_blank" href="https://codepen.io/Peeyush200/pen/mLwvJB">

            </a>
        </h4>
    </div>

</body>
</html>
<script type="text/javascript" src="~/js/validar.js"></script>

ProyectoDesarrollo.B.P/Views/Proyecto/Pagar.cshtml
@model ProyectoDesarrollo.B.P.Models.infoPago
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/pagar.css" />
</head>
<body>
    <h1>Rellene los datos</h1>
    <form asp-controller="" asp-action="" method="post">
        <div class="form-group">
            <label for="formGroupExampleInput">NumTarjeta</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Número de Tarjeta" asp-for="NumTarjeta">
            <span asp-validation-for="NumTarjeta" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="formGroupExampleInput">Fecha</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="MM/AA" asp-for="Fecha">
            <span asp-validation-for="Fecha" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="formGroupExampleInput">CVV</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="CVV" asp-for="CVV">
            <span asp-validation-for="CVV" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="formGroupExampleInput">Nombres</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Nombres" asp-for="Nombres">
            <span asp-validation-for="Nombres" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="formGroupExampleInput">Apellidos</label>
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Apellidos" asp-for="Apellidos">
            <span asp-validation-for="Apellidos" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1" class="form-label">Correo electrónico</label>
            <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" asp-for="Email">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="formGroupExampleInput">Telefono</label>
            <input type="text" class="form-control" Telefono="formGroupExampleInput" placeholder="Teléfono" asp-for="Telefono">
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>







        <div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" value="btn" name="pagar" data-toggle="modal" data-target="#exampleModal">Pagar</button>
                <button type="submit" class="btn btn-primary" value="btn" name="modificar">Modificar</button>
                <a asp-action="Index">Regresar</a>
            </div>
            
        </div>
    </form>
</body>
</html>

ProyectoDesarrollo.B.P/Views/Proyecto/Principal.cshtml
@model IEnumerable<ProyectoDesarrollo.B.P.Models.TbProducto>
<html>
<head>
	<link rel="stylesheet" href="~/css/EstilosPrincipal.css">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>TiendaOnline</title>
	<link rel="stylesheet" href="~/css/Style.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
</head>

<body>

	<div class="barra">
		<div class="elementobarra" role="group">
			
			<button type="button" class="btn btn-default"><a asp-controller="Usuario" asp-action="Login">Inciar Sesión</a></button>
			<button type="button" class="btn btn-default"><a asp-controller="Usuario" asp-action="CerrarSesion">Cerrar Sesión</a></button>
			<button type="button" class="btn btn-default"><a asp-controller="Producto" asp-action="Catalogo">Catalogo</a></button>
			<button type="button" class="btn btn-default"><a asp-controller="TemporalVenta" asp-action="VerCarrito">Ver Carrito</a></button>
		</div>
	</div>

	<header class="header">
		<a href="/Proyecto/Index">

			<img src="/imagen/logo.png" alt="logo" class="logo-img">
		</a>
	</header>
	<div class="Pagina">
		<nav class="elementobarra" role="group">
			<!----button class="btn btn-default" onclick="history.back()"><span class="glyphicon glyphicon-chevron-left"></span></!----button>---->
			<input type="checkbox" id="check">
			<label for="check" class="checkbtn">
				<i class="fas fa-bars"></i>
			</label>
			<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-user"></span><a asp-action="Registro">Registro</a></button>
			<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-shopping-cart"></span><a asp-controller="TemporalVenta" asp-action="VerCarrito">Carrito</a></button>
			<button class="btn btn-default"><span class="glyphicon glyphicon-handbag"></span><a asp-controller="Producto" asp-action="Catalogo">Catálogo</a></button>
		</nav>

		
	</div>
	<!-----------FIN DE NUESSTRO CONTENIDO PRINCIPAL------------>
	<footer class="footer">
		<a class="enlace-footer" href="#">
			<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50" viewBox="0 0 226 226" style=" fill:#000000;">
				<g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
					<path d="M0,226v-226h226v226z" fill="#000000"></path>
					<g fill="#ffffff">
						<path d="M113,18.83333c-52.00825,0 -94.16667,42.15842 -94.16667,94.16667c0,52.00825 42.15842,94.16667 94.16667,94.16667c52.00825,0 94.16667,-42.15842 94.16667,-94.16667c0,-52.00825 -42.15842,-94.16667 -94.16667,-94.16667zM113,37.66667c41.60283,0 75.33333,33.7305 75.33333,75.33333c0,37.04891 -26.77936,67.78251 -62.01758,74.08269v-45.50163h22.27263l3.31054,-25.65673h-25.43603v-16.35042c-0.00001,-7.42034 2.06798,-12.43295 12.70882,-12.43295h13.4445v-22.89795c-6.54458,-0.66858 -13.11551,-0.99361 -19.69776,-0.97477c-19.53017,0 -32.90315,11.92003 -32.90315,33.80436v18.88851h-22.07031v25.65673h22.07031v45.52003c-35.40101,-6.16634 -62.34864,-36.97342 -62.34864,-74.13786c0,-41.60283 33.7305,-75.33333 75.33333,-75.33333z">
						</path>
					</g>
				</g>
			</svg>
		</a>

		<a class="enlace-footer" href="#">
			<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="60" height="60" viewBox="0 0 172 172" style=" fill:#000000;">
				<g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
					<path d="M0,172v-172h172v172z" fill="#000000"></path>
					<g fill="#ffffff">
						<path d="M86,11.46667c-41.09653,0 -74.53333,33.4368 -74.53333,74.53333c0,41.09653 33.4368,74.53333 74.53333,74.53333c41.09653,0 74.53333,-33.4368 74.53333,-74.53333c0,-41.09653 -33.4368,-74.53333 -74.53333,-74.53333zM66.88516,34.4h38.21849c17.91667,0 32.49636,14.57422 32.49636,32.48516v38.21849c0,17.91667 -14.57423,32.49636 -32.48516,32.49636h-38.21849c-17.91667,0 -32.49636,-14.57423 -32.49636,-32.48516v-38.21849c0,-17.91667 14.57422,-32.49636 32.48516,-32.49636zM66.88516,45.86667c-11.58707,0 -21.01849,9.43689 -21.01849,21.02969v38.21849c0,11.58707 9.43689,21.01849 21.02969,21.01849h38.21849c11.58707,0 21.01849,-9.43689 21.01849,-21.02969v-38.21849c0,-11.58707 -9.43689,-21.01849 -21.02969,-21.01849zM112.76302,55.41849c2.10987,0 3.81849,1.70862 3.81849,3.81849c0,2.10987 -1.70862,3.82969 -3.81849,3.82969c-2.10987,0 -3.82969,-1.71982 -3.82969,-3.82969c0,-2.10987 1.71982,-3.81849 3.82969,-3.81849zM86,57.33333c15.8068,0 28.66667,12.85987 28.66667,28.66667c0,15.8068 -12.85987,28.66667 -28.66667,28.66667c-15.8068,0 -28.66667,-12.85987 -28.66667,-28.66667c0,-15.8068 12.85987,-28.66667 28.66667,-28.66667zM86,68.8c-9.4993,0 -17.2,7.7007 -17.2,17.2c0,9.4993 7.7007,17.2 17.2,17.2c9.4993,0 17.2,-7.7007 17.2,-17.2c0,-9.4993 -7.7007,-17.2 -17.2,-17.2z">
						</path>
					</g>
				</g>
			</svg>
		</a>
		<a class="enlace-footer" href="#">
			<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="48" height="48" viewBox="0 0 172 172" style=" fill:#000000;">
				<g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
					<path d="M0,172v-172h172v172z" fill="#000000"></path>
					<g fill="#ffffff">
						<path d="M86,14.33333c-39.5815,0 -71.66667,32.08517 -71.66667,71.66667c0,39.5815 32.08517,71.66667 71.66667,71.66667c39.5815,0 71.66667,-32.08517 71.66667,-71.66667c0,-39.5815 -32.08517,-71.66667 -71.66667,-71.66667zM86,28.66667c31.66233,0 57.33333,25.671 57.33333,57.33333c0,31.66233 -25.671,57.33333 -57.33333,57.33333c-5.27193,0 -10.35229,-0.76706 -15.20117,-2.09961c1.52517,-3.07269 2.8933,-6.3108 3.63933,-9.18229c0.82417,-3.15333 4.19922,-16.01302 4.19922,-16.01302c2.193,4.18533 8.60247,7.74056 15.42513,7.74056c20.30317,0 34.9375,-18.67454 34.9375,-41.88021c0,-22.2525 -18.15294,-38.89876 -41.51628,-38.89876c-29.06083,0 -44.48372,19.50442 -44.48372,40.74642c0,9.87567 5.25496,22.17098 13.66146,26.09115c1.27567,0.59483 1.95975,0.33683 2.25358,-0.89583c0.22933,-0.93883 1.36682,-5.51408 1.87565,-7.64258c0.16483,-0.67367 0.08992,-1.26515 -0.46191,-1.93165c-2.78067,-3.3755 -5.01107,-9.57164 -5.01107,-15.35514c0,-14.8565 11.24584,-29.22656 30.40235,-29.22656c16.54066,0 28.12077,11.27507 28.12077,27.3929c0,18.2105 -9.19573,30.82226 -21.16406,30.82226c-6.60767,0 -11.57114,-5.45574 -9.98015,-12.16374c1.89917,-8.00516 5.58496,-16.64749 5.58496,-22.42383c0,-5.16717 -2.76275,-9.47624 -8.51042,-9.47624c-6.75817,0 -12.19173,6.98213 -12.19173,16.34896c0,5.96267 2.01563,9.99414 2.01563,9.99414c0,0 -6.66903,28.21461 -7.89453,33.46777c-0.60737,2.59249 -0.8101,5.66382 -0.82585,8.73438c-19.05164,-9.32011 -32.20801,-28.8455 -32.20801,-51.48242c0,-31.66233 25.671,-57.33333 57.33333,-57.33333z">
						</path>
					</g>
				</g>
			</svg>
		</a>

		<p>© 2023 E-COMMERCE</p>
	</footer>
		<h2>Contacto</h2>
		<form action="#" method="post">
			<label for="nombre">Nombre:</label>
			<input type="text" id="nombre" name="nombre">
			<label for="correo">Correo electrónico:</label>
			<input type="email" id="correo" name="correo">
			<label for="mensaje">Mensaje:</label>
			<textarea id="mensaje" name="mensaje"></textarea>
			<input type="submit" value="Enviar">
		</form>
	
	<footer>
		<p></p>
		<p></p>
		<p></p>

	</footer>
</body>
</html>

ProyectoDesarrollo.B.P/Views/Proyecto/Registro.cshtml
@model ProyectoDesarrollo.B.P.Models.Usuario

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <LINK REL=StyleSheet HREF="~/css/registro.css" TYPE="text/css" MEDIA=screen>
</head>
<body>
    <div class="container">

        <h1>FORMULARIO DE REGISTRO</h1>
        <form asp-controller="Proyecto" asp-action="ListarUsuario" method="post">
            <div class="form-group">
                <label for="formGroupExampleInput">Id</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="DNI" asp-for="Id">
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Nombre Producto</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Nombre" asp-for="Nombre">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Precio Producto</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Apellido" asp-for="Apellido">
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Stock Producto</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Edad" asp-for="Edad">
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" value="btn" name="grabar" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Grabar</button>
                <button type="submit" class="btn btn-primary" value="btn" name="modificar">Modificar</button>
            </div>
            <div class="form-group">
            </div>
            <div class="text-dark">
                <a asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>

</body>
</html>