ProyectoDesarrollo.B.P/Models/TemporalVenta.cs
namespace ProyectoDesarrollo.B.P.Models
{
    public class TemporalVenta
    {
        public string codigo { get; set; } = null!;
        public string nombre { get; set; }
        public double precio { get; set; }
        public int cantidad { get; set; }
    }
}

ProyectoDesarrollo.B.P/Controllers/DVentaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class DVentaController : Controller
    {
        private readonly IDVenta _Dventa;

        public DVentaController(IDVenta Dventa)
        {
            _Dventa = Dventa;
        }
        private JsonSerializerSettings GetJsonSerializerSettings()
        {
            var settings = new JsonSerializerSettings
            {
                FloatParseHandling = FloatParseHandling.Decimal,
                MissingMemberHandling = MissingMemberHandling.Ignore,
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new SnakeCaseNamingStrategy()
                }
            };

            return settings;
        }
        private string GenerarSiguienteCodigoVenta(string ultimoCodigoVenta)
        {
            string codigoBase = ultimoCodigoVenta.Substring(0, 1); // Obtenemos el primer carácter del código (en este caso, 'V')
            int ultimoNumero = int.Parse(ultimoCodigoVenta.Substring(1)); // Obtenemos el número del último código (por ejemplo, '04')

            int siguienteNumero = ultimoNumero + 1; // Incrementamos el número en 1
            string nuevoNumero = siguienteNumero.ToString("D2"); // Convertimos el número a una cadena de dos dígitos con ceros a la izquierda (por ejemplo, '05')

            return codigoBase + nuevoNumero; // Concatenamos el código base con el nuevo número y retornamos el nuevo código de venta (por ejemplo, 'V05')
        }

        [Obsolete]
        private void GeneratePdf(string htmlContent, string filePath)
        {
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                var document = new Document();
                var writer = PdfWriter.GetInstance(document, stream);
                document.Open();

                var htmlWorker = new HTMLWorker(document);
                using (var sr = new StringReader(htmlContent))
                {
                    htmlWorker.Parse(sr);
                }

                document.Close();
            }
        }
        [HttpPost]
        [Obsolete]
        public IActionResult TransferirDetalles(string detalles, string totalVenta)
        {
            string ultimoCodigoVenta = _Dventa.GetUltimoCodigoVenta();
            string nuevoCodigoVenta = GenerarSiguienteCodigoVenta(ultimoCodigoVenta);


            if (!string.IsNullOrEmpty(detalles))
            {

                var detalleArray = JsonConvert.DeserializeObject<TemporalVenta[]>(detalles);
                TbVenta nuevaVenta = new TbVenta();
                nuevaVenta.CodVenta = nuevoCodigoVenta;
                nuevaVenta.CodCliente = "CL01"; // Asignar el código del cliente según corresponda
                nuevaVenta.FecVenta = DateTime.Now; // Asignar la fecha actual o la fecha deseada
                nuevaVenta.TotalVenta = decimal.Parse(totalVenta); // Calcular el total de la venta según tus requisitos
                nuevaVenta.EstadoVenta = "Activo";
                _Dventa.addBb(nuevaVenta);
                if (detalleArray != null && detalleArray.Count() > 0)
                {
                    foreach (var detalle in detalleArray)
                    {
                        TbDetalleVenta tbDetalle = new TbDetalleVenta();
                        tbDetalle.CodVenta = nuevoCodigoVenta;
                        tbDetalle.CodProducto = detalle.codigo;
                        tbDetalle.Precio = (decimal)detalle.precio;
                        tbDetalle.Cantidad = detalle.cantidad;

                        _Dventa.addBa(tbDetalle);
                    }
                    string htmlContent = @"

            <h3>INFORMACIÓN DE LA COMPRA</h3>
            <h3>DATOS CLIENTE</h3>
            <h6>Nombre y Apellidos: Mayerly Damian Gavino</h6>
            <h6>Direción: Av. Javier Prado</h6>
            <h5>Teléfono: 999 989 878</h5>
            <h5>Dirección de correo electrónico: damian@gmail.com</h5>


            <h3>Datos de la compra</h3>
            <table>
                <tr>
                    <th>Código</th>
                    <th>Descripción</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Subtotal</th>
                </tr>";

                    foreach (var clon in detalleArray)
                    {
                        double subtotalItem = clon.precio * clon.cantidad;
                        htmlContent += $@"
                <tr>
                    <td>{clon.codigo}</td>
                    <td>{clon.nombre}</td>
                    <td>{clon.precio}</td>
                    <td>{clon.cantidad}</td>
                    <td>{Math.Round(subtotalItem, 2)}</td>
                </tr>";
                    }

                    double subtotal = detalleArray.Sum(c => c.precio * c.cantidad);
                    double igv = subtotal * 0.18;
                    double total = subtotal + igv;

                    htmlContent += $@"
            </table>
            <div class='subtotal'>
                Subtotal: {Math.Round(subtotal, 2)}
            </div>
            <div class='igv'>
                IGV (18%): {Math.Round(igv, 2)}
            </div>
            <div class='total'>
                Total: {Math.Round(total, 2)}
            </div>";
                    var filePath = "C:\\Users\\dell\\Desktop\\PDF_DBP\\" + nuevoCodigoVenta;
                    filePath += ".pdf";
                    // Generar el PDF
                    GeneratePdf(htmlContent, filePath);
                    return RedirectToAction("Index", "Venta");
                }
            }
            return RedirectToAction("Catalogo", "Producto");
        }
        public IActionResult Boleta()
        {
            return View();
        }
    }
}

ProyectoDesarrollo.B.P/Controllers/TemporalVentaController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class TemporalVentaController : Controller
    {
        private readonly iTemporalVenta _temporalVenta;

        public TemporalVentaController(iTemporalVenta temporalVenta)
        {
            _temporalVenta = temporalVenta;
        }

        public IActionResult Index(string txtcodigo, string txtdescripcion, string txtprecio, string txtcantidad)
        {
            TemporalVenta obj = new TemporalVenta();
            int  productoExistente = _temporalVenta.ObtenerProductoPorCodigo(txtcodigo);

            if (productoExistente != -1)
            {

                _temporalVenta.AumentarCantidadProducto(txtcodigo, int.Parse(txtcantidad));
  
            }
            else
            {  
               
                obj.codigo = txtcodigo;
                obj.nombre = txtdescripcion;
                obj.precio = double.Parse(txtprecio);
                obj.cantidad = int.Parse(txtcantidad);

                _temporalVenta.agregar(obj);
           }

            return RedirectToAction("Catalogo", "Producto");
        }

      
        [Route("TemporalVenta/VerCarrito/{Codigo}")]
        public IActionResult EliminarProducto(string codigo)
        {
            _temporalVenta.EliminarProducto(codigo);

            return RedirectToAction("VerCarrito");
        }
        public IActionResult VerCarrito()
        {
            return View(_temporalVenta.ListarTemporalVenta());
        }
        public IActionResult VerCombo()
        {
            return View();
        }

        public IActionResult VerDetalle()
        {
            return View(_temporalVenta.ListarTemporalVenta());
        }
    }
}

ProyectoDesarrollo.B.P/Views/TemporalVenta/VerCarrito.cshtml
@using Newtonsoft.Json
@model IEnumerable<ProyectoDesarrollo.B.P.Models.TemporalVenta>
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
           
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f2f2f2;
        }

        h3 {
            color: #333;
            margin-bottom: 10px;
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 4px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            font-weight: bold;
        }

        td {
            color: #333;
        }

        input[type="number"] {
            width: 50px;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin-top: 10px;
            cursor: pointer;
            border-radius: 4px;
        }

        .message {
            margin-top: 10px;
            color: #f00;
            font-style: italic;
        }

        .total {
            text-align: right;
            margin-top: 20px;
            font-weight: bold;
        }

        .subtotal {
            text-align: right;
            margin-top: 10px;
        }

        .igv {
            text-align: right;
        }
        </style>
   
</head>
<body>
    <h3>CARRITO DE COMPRAS</h3>
    <table>
        <tr>
            <th>Código</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th></th> <!-- Columna para el botón de eliminar -->
        </tr>
        <tbody>
            @foreach (var clon in Model)
            {
                <tr>
                    <td>@clon.codigo</td>
                    <td>@clon.nombre</td>
                    <td>@clon.precio</td>
                    <td>@clon.cantidad</td>
                    <td>
                        <form asp-controller="TemporalVenta" asp-action="VerCarrito" asp-route-id="@clon.codigo" method="post">
                            <input type="hidden" name="codigo" value="@clon.codigo" />
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </td>
                </tr>

            }
            <tr>
                <td colspan="5" style="text-align: right;">
                    <form asp-controller="Usuario" asp-action="Login" method="post">
                        <button type="submit" class="btn btn-primary">Comprar</button>
                    </form>

                </td>
            </tr>
        </tbody>
    </table>
    @{
        double subtotal = Model.Sum(c => (c.precio * c.cantidad) - (c.precio * c.cantidad * 0.18));
        double igv = Model.Sum(c => c.precio * c.cantidad * 0.18);
        double total = Model.Sum(c => c.precio * c.cantidad);
    }

    <div class="subtotal">
        Subtotal: @Math.Round(subtotal, 2)
    </div>
    <div class="igv">
        IGV: @Math.Round(igv, 2)
    </div>
    <div class="total">
        Total: @Math.Round(total, 2)
    </div>
</body>

</html>

ProyectoDesarrollo.B.P/Views/TemporalVenta/VerCombo.cshtml
@using Newtonsoft.Json
@model IEnumerable<ProyectoDesarrollo.B.P.Models.TemporalVenta>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
</head>
<body>
    <h2>COMBO PARA LOS CLIENTES</h2>
    @foreach(var clon in Model)
    {
        double subtotalItem = clon.precio * clon.cantidad;
        <select name="select">
            <option value="">
                @{

                    @clon.codigo
                    ;
                    @clon.nombre
                    ;
                    @clon.precio
                    ;
                    @clon.cantidad
                    ;
                    @Math.Round(subtotalItem, 2)
                }
            </option>
        </select>
        
    }
    

</body>
</html>

ProyectoDesarrollo.B.P/Views/TemporalVenta/VerDetalle.cshtml
@using Newtonsoft.Json
@model IEnumerable<ProyectoDesarrollo.B.P.Models.TemporalVenta>
<html>
<head>
    <style>
        body {
            background-image: url(https://img.freepik.com/vector-gratis/patron-colorido-garabatos-animales-palabras_52683-6875.jpg?w=740&t=st=1687837666~exp=1687838266~hmac=bf269eb03bcf1e0698979337723bcad1dc3ff42b980a1a922d4e9fbed6061462);
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f2f2f2;
        }

        .container {
            width: 700px;
            margin: 0 auto;
            background-color: #fff;
            padding: 15px;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h3 {
            color: #333;
            margin-bottom: 10px;
            font-size: 24px;
            font-weight: bold;
            text-align: center;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 4px;
        }
        h6{
            font-weight: bold;
            font-size: 16px;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            font-weight: bold;
        }

        td {
            color: #333;
        }

        .subtotal {
            text-align: right;
            margin-top: 10px;
        }

        .igv {
            text-align: right;
        }

        .total {
            text-align: right;
            margin-top: 20px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        
        <h3>INFORMACIÓN DE LA COMPRA</h3>
        <h3>DATOS CLIENTE</h3>
        <h6>Nombre y Apellidos: Mayerly Damian Gavino</h6>
        <h6>Direción: Av. Javier Prado</h6>
        <h6>Teléfono: 999 989 878</h6>
        <h6>Dirección de correo electrónico: damian@gmail.com</h6>

        <h3>Datos de la compra</h3>
        <table>
            <tr>
                <th>Código</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
            </tr>
            <tbody>
                @foreach (var clon in Model)
                {
                    double subtotalItem = clon.precio * clon.cantidad;
                    <tr>
                        <td>@clon.codigo</td>
                        <td>@clon.nombre</td>
                        <td>@clon.precio</td>
                        <td>@clon.cantidad</td>
                        <td>@Math.Round(subtotalItem, 2)</td>
                    </tr>
                }
            </tbody>
            
        </table>
        @{
            double subtotal = Model.Sum(c => c.precio * c.cantidad);
            double igv = subtotal * 0.18;
            double total = subtotal + igv;
        }
        <div class="subtotal">
            Subtotal: @Math.Round(subtotal, 2)
        </div>
        <div class="igv">
            IGV (18%): @Math.Round(igv, 2)
        </div>
        <div class="total">
            Total: @Math.Round(total, 2)
        </div>

        <form asp-controller="DVenta" asp-action="TransferirDetalles" method="post">
            <input type="hidden" name="totalVenta" value="@Math.Round(total, 2)" />
            <input type="hidden" name="detalles" value='@JsonConvert.SerializeObject(Model)' />
            <button type="submit" class="btn btn-primary">Finaliza Compra</button>
        </form>
    </div>
</body>
</html>