ProyectoDesarrollo.B.P/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoDesarrollo.B.P.Models
{
    public class Usuario
    {
        [Required(ErrorMessage = "El campo DNI es obligatorio")]
        public string Id { get; set; }
        [Required(ErrorMessage = "El campo del NOMBRES es obligatorio")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo de los APELLIDOS es obligatorio")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "El campo de EDAD es obligatorio")]
        public string Edad { get; set; }

        public int IdUsuario { get; set; }

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuNombre { get; set; } = null!;

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuClave { get; set; } = null!;

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuNomApe { get; set; } = null!;

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuDirec { get; set; } = null!;

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuTelef { get; set; } = null!;

        [Required(ErrorMessage = "Este campo es OBLIGATORIO")]
        public string UsuEmail { get; set; } = null!;
    }
}

ProyectoDesarrollo.B.P/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class UsuarioController : Controller
    {

        // Version Mayerly
        private readonly IUsuario _usuario;

        public UsuarioController(IUsuario usuario)
        {
            _usuario = usuario;
           
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult GrabarDatos(Usuario obj)
        {
            _usuario.Add(obj);
            return RedirectToAction("ListarUsuarios");
        }

        public IActionResult ValidarUsuario(Usuario obj)
        {
            if (_usuario.ValidateUser(obj) == true)
            {
                HttpContext.Session.SetString("sUsuario", JsonConvert.SerializeObject(obj)); 
                return RedirectToAction("VerDetalle", "TemporalVenta"); // carrito de compras
                
            }
            else
            {
                return View("Login");
            }

        }

        public IActionResult CerrarSesion()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Usuario");
        }

        // MOSTRANDO LA LISTA DE USUARIOS REGISTRADOS
        public IActionResult ListarUsuarios()
        {
            return View(_usuario.GellAllUser());
        }

    }
}

ProyectoDesarrollo.B.P/Controllers/UsuarioRegistroController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDesarrollo.B.P.Models;
using ProyectoDesarrollo.B.P.Services;

namespace ProyectoDesarrollo.B.P.Controllers
{
    public class UsuarioRegistroController : Controller
    {
        private readonly iUsuarioRegistro _usuario;
        public UsuarioRegistroController(iUsuarioRegistro registro)
        {
            _usuario = registro;
        }

        public IActionResult RegistroUsuarios()
        {
            return View(_usuario.GetAllUsers());
        }

        [Route("UsuarioRegistro/Eliminar/{id}")]
        public IActionResult Eliminar(string id) 
        {
            _usuario.eliminar(id);
            return RedirectToAction("RegistroUsuarios");
        }

        public IActionResult Nuevo() 
        { 
            return View(); 
        }
        public IActionResult Grabar(TbUsuario obj)
        {
            _usuario.agregar(obj);
            return RedirectToAction("RegistroUsuarios");
        }


        [Route("UsuarioRegistro/Modificar/{id}")]
        public IActionResult Modificar(string id)
        {
            var obj = _usuario.editar(id);
            return View(obj);
        }

        public IActionResult ModificarUsuario(TbUsuario obj)
        {
            _usuario.editarDetalles(obj);
            return RedirectToAction("RegistroUsuarios");
        }

        /*public IActionResult CargarDatos()
        {
            return View();
        }*/
    }
}

ProyectoDesarrollo.B.P/Views/Usuario/ListarUsuarios.cshtml
@model IEnumerable<ProyectoDesarrollo.B.P.Models.Usuario>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
<head>

</head>
<body>

    <h3 class="">LISTADO DE USUARIOS</h3>
    <table class="table table-bordered">
        <tr>
            <td>ID</td>
            <td>NOMBRE DE USUARIO</td>
            <td>CLAVE DEL USUARIO</td>

            <td>Nombres y Apellidos</td>
            <td>Direccion</td>
            <td>Teléfono</td>
            <td>Correo electrónico</td>
            <td>Eliminar</td>
            <td>Modificar</td>
        </tr>
        <tbody id="myTable">
            @foreach (var clon in Model)
            {
                <tr>
                    <td>@clon.Id</td>
                    <td>@clon.UsuNombre</td>
                    <td>@clon.UsuClave</td>
                    <td>@clon.UsuNomApe</td>
                    <td>@clon.UsuDirec</td>
                    <td>@clon.UsuTelef</td>
                    <td>@clon.UsuEmail</td>
                    <td><a asp-action="Eliminar" asp-route-id="@clon.Id">Eliminar</a></td>
                    <td><a asp-action="Modificar" asp-route-id="@clon.Id">Editar</a></td>
                </tr>
            }
        </tbody>
    </table>

    


</body>
</html>

<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

ProyectoDesarrollo.B.P/Views/Usuario/Login.cshtml
@model ProyectoDesarrollo.B.P.Models.Usuario
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
<head>
    <link rel="stylesheet" href="~/css/LoginUsu.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <form class="form-signin" asp-controller="Usuario" asp-action="ValidarUsuario" id='valForm' method="post">
            <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
            <h2 class="form-signin-heading">Sign in</h2>
            <label for="inputEmail" class="sr-only">Username</label>
            <input type="text" class="form-control" placeholder="Username"
                   asp-for="UsuNombre" id="username" />
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" class="form-control" placeholder="Password"
                   asp-for="UsuClave" id="password" />
            <button class="btn btn-lg btn-primary btn-block" type="submit">
                <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Sign in
            </button>
        </form>
        
        <div class="form-signin-heading">
            <div class="text-dark">
                <b><a asp-controller="UsuarioRegistro" asp-action="Nuevo">Registrarme</a></b>
            </div>
        </div>
   
</body>
</html>